---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--exp
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--exp
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /gpfs/slac/cryo/fs1/daq/dev/exp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        #- key: kubernetes.io/hostname
        - key: storage/cryoem
          operator: In
          values:
          - 'true'
          #- ocio-gpu02
          # - cryoem-daq01
          # - cryoem-daq02
          # - cryoem-daq03
          # - cryoem-daq04
          # - cryoem-daq05

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--exp
spec:
  storageClassName: cryoem-daq-dev--exp
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem1
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem1-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem1-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1
spec:
  storageClassName: cryoem-daq-dev--tem1
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem1-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem1-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem2/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem2-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem2-gainrefs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2
spec:
  storageClassName: cryoem-daq-dev--tem2
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem2-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem2-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem3
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem3/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem3-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem3-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05
          
          
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3
spec:
  storageClassName: cryoem-daq-dev--tem3
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem3-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem3-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem4
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem4/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4-gainrefs
  labels:
    type: local
spec:
  storageClassName: cryoem-daq-dev--tem4-gainrefs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /srv/cryoem/tem4-gainrefs/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocio-gpu02
          #- cryoem-daq01
          #- cryoem-daq02
          #- cryoem-daq03
          #- cryoem-daq04
          #- cryoem-daq05
          

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4
spec:
  storageClassName: cryoem-daq-dev--tem4
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-dev--tem4-gainrefs
spec:
  storageClassName: cryoem-daq-dev--tem4-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
