apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1 
  template:
    spec:
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: cryoem-daq-dev--dags
      - name: airflow-plugins
        persistentVolumeClaim:
          claimName: cryoem-daq-dev--plugins
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: cryoem-daq-dev--logs
      containers:
      - name: scheduler
        env:
        - name: AIRFLOW_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-www
              key: admin-password
