apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: cryoem-daq-dev--dags
      - name: airflow-plugins
        persistentVolumeClaim:
          claimName: cryoem-daq-dev--plugins
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: cryoem-daq-dev--logs
      containers:
      - name: webserver 
        env:
        - name: AIRFLOW_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: www
              key: admin-password
---

