---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: www2
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  tls:
  - hosts:
    - cryoem-test.slac.stanford.edu
    secretName: test
  rules:
  - host: cryoem-test.slac.stanford.edu
    http:
      paths:
      - path: /
        backend:
          serviceName: www
          servicePort: 8080
