---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 0 
  selector:
    matchLabels:
      role: worker
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        role: worker
    spec:
      securityContext:
        runAsUser: 15693
        runAsGroup: 3591
        #fsGroup:
      containers:
      - name: worker
        image: slaclab/cryoem-airflow:20200317.0
        imagePullPolicy: Always
        #livenessProbe:
        #  httpGet:
        #    path: /admin
        #    port: 8080
        #  initialDelaySeconds: 2 
        #  periodSeconds: 10
        #readinessProbe:
        #  httpGet:
        #    path: /admin
        #    port: 8080
        #  initialDelaySeconds: 2 
        #  periodSeconds: 10
        env:
        - name: AIRFLOW_MODE
          value: "worker -q dtn,default"
        - name: POSTGRES_SERVICE_HOST
          #value: postgres
          #value: pgpool
          valueFrom:
            configMapKeyRef:
              name: postgres
              key: db_url
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres
              key: database
        - name: REDIS_SERVICE_HOST
          value: redis
        #- name: REDIS_CONFIG
        #  valueFrom:
        #    secretKeyRef:
        #      name: redis
        #      key: redis-config
        - name: FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow
              key: fernet-key
        volumeMounts:
        - name: airflow-dags
          mountPath: /usr/local/airflow/dags
        - name: airflow-plugins
          mountPath: /usr/local/airflow/plugins
        - name: airflow-logs
          mountPath: /usr/local/airflow/logs
        - name: exp
          mountPath: /gpfs/slac/cryo/fs1/exp/
        #- name: sdf-exp
        #  mountPath: /sdf/group/cryoem/exp/
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: cryoem-daq-prod--sdf-dags
      - name: airflow-plugins
        persistentVolumeClaim:
          claimName: cryoem-daq-prod--sdf-plugins
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: cryoem-daq-prod--sdf-logs
      - name: exp
        persistentVolumeClaim:
          claimName: cryoem-daq-prod--exp
      #- name: sdf-exp
      #  persistentVolumeClaim:
      #    claimName: cryoem-daq-prod--sdf-exp
