---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sdf-group-cryoem
spec:
  storageClassName: sdf-group-cryoem
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 100Gi

---
