
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-exp
spec:
  storageClassName: sdf-group-cryoem-exp
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-fib1
spec:
  storageClassName: srv-cryoem-fib1
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem1
spec:
  storageClassName: srv-cryoem-tem1
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem1-gainrefs
spec:
  storageClassName: srv-cryoem-tem1-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem2
spec:
  storageClassName: srv-cryoem-tem2
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem2-gainrefs
spec:
  storageClassName: srv-cryoem-tem2-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem3
spec:
  storageClassName: srv-cryoem-tem3
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem3-gainrefs
spec:
  storageClassName: srv-cryoem-tem3
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem4
spec:
  storageClassName: srv-cryoem-tem4
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tem4-gainrefs
spec:
  storageClassName: srv-cryoem-tem4-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-temalpha
spec:
  storageClassName: srv-cryoem-temalpha
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tembeta
spec:
  storageClassName: srv-cryoem-tembeta
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-tembeta-gainrefs
spec:
  storageClassName: srv-cryoem-tembeta-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-temgamma
spec:
  storageClassName: srv-cryoem-temgamma
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-daq-temgamma-gainrefs
spec:
  storageClassName: srv-cryoem-temgamma-gainrefs
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi

