apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: www-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  rules:
  - host: cryoem-daq.slac.stanford.edu
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: www
            port:
              number: 8080
        path: /
  #tls:
  #- hosts:
  #  - cryoem-daq.slac.stanford.edu
  #  secretName: www
