namespace: cryoem-daq--prod

bases:
- ../../base

resources:
- ns.yaml
- ingress.yaml
- cryoem-storage.yaml
- database-storage.yaml
- messagebus-storage.yaml
- airflow-storage.yaml
#- workers.yaml
#- dtns.yaml

patchesStrategicMerge:
- database-patch.yaml
- scheduler-patch.yaml
- webserver-patch.yaml
- messagebus-patch.yaml
#- worker-patch.yaml

secretGenerator:
- name: postgres
  files:
  - etc/root-password
  - etc/primary-password
  - etc/password
  literals:
  - primary-username=repl
  - username=airflow
- name: redis
  files:
  - password=etc/redis-password
- name: airflow
  files:
  - etc/fernet-key
- name: www
  files:
  - admin-password=etc/airflow-admin-password
 

configMapGenerator: 
- name: postgres
  literals: 
  - db_url=postgres
  - database=airflow

images:
- name: slaclab/cryoem-airflow
  # 1.10.9 (prod)
  newTag: '20200404.0'
- name: slaclab/cryoem-airflow-dtn
  # kill zombies
  newTag: '20220519.0'
