apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: internal
    metallb.universe.tf/allow-shared-ip: cryoem-daq
  name: redis
#spec:
#  loadBalancerIP: 172.23.99.151


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-primary
spec:
  selector:
    matchLabels:
      role: messagebus
  replicas: 1
  template:
    metadata:
      labels:
        role: messagebus
    spec:
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: cryoem-daq-redis
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 15693
        runAsGroup: 3591
      containers:
      - name: redis-primary
        image: redis:7.0.4-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis-primary
        volumeMounts:
        - name: redis-data
          mountPath: /data
        args: ["redis-server", "--appendonly", "yes", "--requirepass", "$(REDIS_PASSWORD)"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
