apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: airflow-root
        persistentVolumeClaim:
          claimName: sdf-group-cryoem
      containers:
      - name: webserver 
        env:
        - name: PG_DATABASE_RW_SERVICE_HOST
          value: postgres-rw
        - name: AIRFLOW_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: www
              key: airflow-admin-password
        volumeMounts:
        - name: airflow-root
          mountPath: /usr/local/airflow/dags
          subPath: daq/prod/airflow/dags
        - name: airflow-root
          mountPath: /usr/local/airflow/plugins
          subPath: daq/prod/airflow/plugins
        - name: airflow-root
          mountPath: /usr/local/airflow/logs
          subPath: daq/prod/airflow/logs
          
---

