---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--postgres--${environment}-0
  labels:
    type: local
spec:
  storageClassName: ${namespace}--postgres--${environment}
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  #hostPath:
  local:
    path: ${database__prefix_path}/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cryoem-db01


#
