---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${namespace}--postgres--${environment}-0
  labels:
    type: local
spec:
  storageClassName: ${namespace}--postgres--${environment}
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${database__prefix_path}/

#
