---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: worker
    spec:
      nodeSelector:
$(list=(${worker__nodeSelectors// / }); for k in "${!list[@]}"; do kv=(${list[k]//\=/ }); echo "        ${kv[0]}: ${kv[1]}"; done)
      containers:
      - name: worker
        image: yee379/airflow-docker:${worker__tag}
        imagePullPolicy: Always
        #livenessProbe:
        #  httpGet:
        #    path: /admin
        #    port: 8080
        #  initialDelaySeconds: 2 
        #  periodSeconds: 10
        #readinessProbe:
        #  httpGet:
        #    path: /admin
        #    port: 8080
        #  initialDelaySeconds: 2 
        #  periodSeconds: 10
        env:
          - name: JUPYTERHUB_USER
            value: "${airflow_user}"
          - name: EXTERNAL_UID
            value: "${airflow_uid}"
          - name: EXTERNAL_GROUPS
            value: "${airflow_external_groups}"
          - name: AIRFLOW_MODE
            value: worker
          - name: FERNET_KEY
            value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
        volumeMounts:
          - name: airflow-dags
            mountPath: /usr/local/airflow/dags
          - name: airflow-plugins
            mountPath: /usr/local/airflow/plugins
          - name: airflow-logs
            mountPath: /usr/local/airflow/logs
          - name: ssh-key
            mountPath: /usr/local/airflow/.ssh/
          - name: exp
            mountPath: "${cryoem_exp__prefix_path}" 
          - name: tem1
            mountPath: /srv/cryoem/tem1
          - name: tem2
            mountPath: /srv/cryoem/tem2
          - name: tem3
            mountPath: /srv/cryoem/tem3
          - name: tem4
            mountPath: /srv/cryoem/tem4
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: ${namespace}--dags--${environment}
        - name: airflow-plugins
          persistentVolumeClaim:
            claimName: ${namespace}--plugins--${environment}
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: ${namespace}--logs--${environment}
        - name: ssh-key
          secret:
            secretName: ssh-key
            items:
              - key: ssh_key
                path: ssh_key
        - name: exp
          persistentVolumeClaim:
            claimName: ${namespace}--exp--${environment}
        - name: tem1
          persistentVolumeClaim:
            claimName: ${namespace}--tem1--${environment}
        - name: tem2
          persistentVolumeClaim:
            claimName: ${namespace}--tem2--${environment}
        - name: tem3
          persistentVolumeClaim:
            claimName: ${namespace}--tem3--${environment}
        - name: tem4
          persistentVolumeClaim:
            claimName: ${namespace}--tem4--${environment}

